* write my own blog
** TODO new blogs [1/6]
1. [X] box-sizing
2. [ ] box-shadow 学习
3. [ ] height 设值无法成功的问题
4. [ ] height vs padding （height 失效）
5. [ ] 下拉动画
6. [ ] box-shadow 阴影被覆盖 https://stackoverflow.com/questions/5505118/css-box-shadow-hidden-z-index-does-not-fix


** new blog on css <2020-09-10 四>

border/padding vs width/height

事情源自于工作上遇到的一个问题： 我想要实现一个下拉动画，但是发现遇到了一个 bug，有个下拉元素 出现了小片空白。

经过排查，发现是由 css 的 padding 属性引起的 bug。接下来先给出代码，描述问题之后，列出相关知识点，再说明解决方案。

*** box-sizing
MDN: [[https://developer.mozilla.org/en-US/docs/Web/CSS][CSS]] 中的 box-sizing 属性定义了 [[https://developer.mozilla.org/zh-CN/docs/Glossary/User_agent][user agent]] 应该如何计算一个元素的总宽度和总高度。
在 CSS 盒子模型的默认定义里，你对一个元素所设置的 width 与 height 只会应用到这个元素的内容区。如果这个元素有任何的 border 或 padding ，
绘制到屏幕上时的盒子宽度和高度会加上设置的边框和内边距值。这意味着当你调整一个元素的宽度和高度时需要时刻注意到这个元素的边框和内边距。当我们实现响应式布局时，这个特点尤其烦人。

box-sizing 使得计算高度宽度变得简单，它有两个可赋值的属性

- content-box  是默认值。如果你设置一个元素的宽为100px，那么这个元素的内容区会有100px 宽，并且任何边框和内边距的宽度都会被增加到最后绘制出来的元素宽度中。
- border-box 告诉浏览器：你想要设置的边框和内边距的值是包含在width内的。也就是说，如果你将一个元素的width设为100px，那么这100px会包含它的border和padding，内容区的实际宽度是
width减去(border + padding)的值。大多数情况下，这使得我们更容易地设定一个元素的宽高。

*** box-shadow

*** height 设值
    
*** height vs padding (height 失效)

** new blog on html
